### ISSUE TITLE
one_key_install运行之后没有输入密码就自签结束了

### ISSUE THREAD

**Issue by dingjie03** [V5zhou/ZZXcodeFormat#4]
agent xx$ /Users/xx/Documents/三方代码库/ZZXcodeFormat/one_key_install
/Users/xx/Documents/三方代码库/ZZXcodeFormat
clang-format配置文件已存在\n
开始获取xcode的uuid
获取到xcode的uuid为:426A087B-D3AA-431A-AFDF-F135EC00DE1C\n
已存在xcode_uuid:426A087B-D3AA-431A-AFDF-F135EC00DE1C\n
开始编译插件
编译完成\n
开始对xcode进行自签，请输入mac密码
自签结束\n

**Comment by dingjie03** [comment]
```
# 开始对xcode进行自签
echo "开始对xcode进行自签，请输入mac密码"
# sudo codesign -f -s XcodeSigner /Applications/Xcode.app
echo "自签结束\n"
```

sudo codesign -f -s XcodeSigner /Applications/Xcode.app被注释了。。去掉注释

**Comment by V5zhou** [comment]
你好，确实是误上传了#，多谢提醒！
